run:
  modules-download-mode: readonly
  timeout: 5m
issues:
  exclude-files:
    - "benchmark_test.go"
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - goconst
    - gocritic
    - gocyclo
    # False positives with range-over-func: https://github.com/alexkohler/prealloc/issues/29
    #- prealloc
    - unconvert
    - unparam
